### ISSUE TITLE
Panic-Message / Break by Step 4

### ISSUE THREAD

**Issue by moonrockets** [frett27/docker-nodemcu-esp32-build#1]
Hi frett27,
any idea to this messages:

Step 3 : WORKDIR /opt
 ---> Running in 7abd74071915
 ---> 799cccdfbebc
Removing intermediate container 7abd74071915
Step 4 : RUN wget http://ftp.gnu.org/gnu/make/make-4.0.tar.gz
 ---> Running in e4a90601bada
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x830c5c0, 0x975b4940)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x975ad96c)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x24d
panic(0x830c5c0, 0x975b4940)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x40b
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x975ad600, 0x97508908, 0x975ad680)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xea
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x9752ef90, 0x8476450, 0x975b4940)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x3f2
main.glob..func8(0x97546460, 0x0, 0x0)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x57
reflect.Value.call(0x82eb8a0, 0x836bf00, 0x13, 0x83361f2, 0x4, 0x975ad92c, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.7/src/reflect/value.go:434 +0xdd7
reflect.Value.Call(0x82eb8a0, 0x836bf00, 0x13, 0x975ad92c, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.7/src/reflect/value.go:302 +0x8c
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x82eb8a0, 0x836bf00, 0x97546460, 0x0, 0x0)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x1ff
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x83363be, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x834770d, 0x51, 0x0, ...)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xcb3
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x97554240, 0x974fa090, 0x2, 0x2, 0x0, 0x0)
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x860
main.main()
	/build/runc-GuaCX9/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main.go:137 +0xae3
The command '/bin/sh -c wget http://ftp.gnu.org/gnu/make/make-4.0.tar.gz' returned a non-zero code: 2

**Comment by frett27** [comment]
seems to be docker related : https://github.com/moby/moby/issues/7924
